name: GitHub Pages

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code repository
        uses: actions/checkout@v3

      - name: install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: install dependencies
        run: pnpm install

      - name: setup docs
        run: pnpm run docs:build

      - name: setup efeplus
        run: pnpm run build:efe-plus

      - name: publish efeplus
        run: pnpm run publish:efe-plus

      - name: gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: saonan90077/saonan90077.github.io
          publish_branch: main
          publish_dir: ./docs/.vitepress/dist
